version: "3"

volumes:
  acme_:

services:
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: $COMPOSE_PROJECT_NAME.acme
    depends_on:
      - nginx
      - dockergen
    restart: unless-stopped
    networks:
      - edge
    volumes_from:
      - nginx
    volumes:
      - acme_:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=${DEFAULT_EMAIL}
      - NGINX_DOCKER_GEN_CONTAINER=$COMPOSE_PROJECT_NAME.dockergen
      - NGINX_PROXY_CONTAINER=$COMPOSE_PROJECT_NAME.nginx
