version: "3"

networks:
  tier_0: ## Outside world
  tier_1: ## Inside proxy

volumes:
  nginx_:
  vhost_:
  certs_:
  html_:

services:
  ###########
  ## PROXY ##
  ###########
  nginx:
    image: ${REGISTRY}/nginx:latest
    container_name: $COMPOSE_PROJECT_NAME.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    networks:
      - tier_0
      - tier_1
    volumes:
      - vhost_:/etc/nginx/vhost.d
      - nginx_:/etc/nginx/conf.d
      - certs_:/etc/nginx/certs
      - html_:/usr/share/nginx/html

  dockergen:
    image: ${REGISTRY}/dockergen:latest
    container_name: $COMPOSE_PROJECT_NAME.dockergen
    restart: always
    command: -notify-sighup $COMPOSE_PROJECT_NAME.nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    networks:
      - tier_0
      - tier_1
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
