version: "3"

services:
  portainer:
    image: "portainer/portainer-ee"
    container_name: $COMPOSE_PROJECT_NAME.portainer
    restart: unless-stopped
    env_file:
      - .env.node.management
    environment:
      - VIRTUAL_PORT=9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/data/portainer/services.progress44.com/data:/data
    networks:
      - tier_0

  watchtower:
    image: "containrrr/watchtower"
    container_name: $COMPOSE_PROJECT_NAME.watchtower
    env_file:
      - .env.node.management
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "3 0 * * * *"

networks:
  tier_0:
    name: network_tier_0
  tier_1:
    name: network_tier_1
