#!/bin/bash
set -eo pipefail
shopt -s nullglob

# if command starts with an option, prepend sshd
if [ "${1:0:1}" = '-' ]; then
	set -- /usr/sbin/sshd "$@"
fi

_datadir() {
	"$@" --verbose --help 2>/dev/null | awk '$1 == "datadir" { print $2; exit }'
}

echo "Connect to ssh authenticating with $SSH_USERNAME:$SSH_PASSWORD"

if [ -n "$SSH_USERNAME" -a -n "$SSH_PASSWORD" ]; then
	echo "$SSH_USERNAME:$SSH_PASSWORD" | chpasswd
fi

exec "$@"