name: Build and Push
on: 
  - push

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Add checkout"
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Pull & update submodules recursively
        run: |
          git submodule update --init --recursive
          git submodule update --recursive --remote
      - name: "Build and push"
        run: make
