name: ci
on: 
  - push

jobs: 
  login:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build & push"
        uses: actions/checkout@v2
        run: make
